'use client';

import React, { useState, useRef } from 'react';
import NavigationHeader from '@/components/NavigationHeader';
import { 
  Landmark, 
  Calendar, 
  Download, 
  CheckCircle2, 
  AlertCircle, 
  FileSpreadsheet, 
  Printer, 
  ShieldCheck, 
  HelpCircle,
  FileText,
  Loader2,
  Building2,
  DollarSign
} from 'lucide-react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function RemittancePage() {
  const [period, setPeriod] = useState('August 2026');
  const [rpNumber, setRpNumber] = useState('84920 1829 RP0001');
  const [employerName, setEmployerName] = useState('Luc Valade (Self-Managed Employer)');
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
  const [copiedStatus, setCopiedStatus] = useState(false);

  const cardRef = useRef<HTMLDivElement>(null);

  // Remittance figures calculated per CRA PD7A guidelines
  const remittanceData = {
    dueDate: 'September 15, 2026',
    employeesCount: 3,
    grossPayroll: 4210.00,
    cppEmployee: 215.30,
    cppEmployer: 215.30, // 1.0x match
    eiEmployee: 69.80,
    eiEmployer: 97.72, // 1.4x match
    incomeTax: 380.40,
    totalRemittance: 978.52,
    ciltQuarterlyAllocation: 1052.50
  };

  // 1-Click PDF Generation using jsPDF and html2canvas
  const handleDownloadPdf = async () => {
    if (!cardRef.current) return;
    setIsGeneratingPdf(true);
    try {
      const canvas = await html2canvas(cardRef.current, {
        scale: 2,
        useCORS: true,
        backgroundColor: '#ffffff'
      });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', 0, 10, pdfWidth, pdfHeight);
      pdf.save(`CRA_PD7A_Remittance_${period.replace(/\s+/g, '_')}_${rpNumber.replace(/\s+/g, '')}.pdf`);
    } catch (err) {
      console.error('Failed to generate PDF:', err);
      // Fallback print
      window.print();
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  // 1-Click CSV Generation
  const handleDownloadCsv = () => {
    const csvRows = [
      ['Receiver General for Canada - CRA Monthly Payroll Remittance Summary (Form PD7A)'],
      ['Employer Name', employerName],
      ['CRA Payroll Business Number (RP)', rpNumber],
      ['Remittance Period', period],
      ['Remittance Due Date', remittanceData.dueDate],
      [''],
      ['Item / Description', 'Amount (CAD)'],
      ['Active Employees in Period', remittanceData.employeesCount],
      ['Gross Payroll for Month', remittanceData.grossPayroll.toFixed(2)],
      ['Employee CPP Deduction', remittanceData.cppEmployee.toFixed(2)],
      ['Employer CPP Matching (1.0x)', remittanceData.cppEmployer.toFixed(2)],
      ['Employee EI Premium', remittanceData.eiEmployee.toFixed(2)],
      ['Employer EI Matching (1.4x)', remittanceData.eiEmployer.toFixed(2)],
      ['Total Federal & Provincial Income Tax Withheld', remittanceData.incomeTax.toFixed(2)],
      ['TOTAL CRA REMITTANCE PAYABLE', remittanceData.totalRemittance.toFixed(2)],
      ['CILT / Direct Funding Quarterly Allocation', remittanceData.ciltQuarterlyAllocation.toFixed(2)],
      [''],
      ['Generated By', 'DirectCare Hub - Canadian Consumer-Directed Payroll Engine'],
      ['Timestamp', new Date().toISOString()]
    ];

    const csvContent = 'data:text/csv;charset=utf-8,' + csvRows.map(e => e.join(',')).join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `CRA_PD7A_Remittance_${period.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopyRp = () => {
    navigator.clipboard.writeText(rpNumber);
    setCopiedStatus(true);
    setTimeout(() => setCopiedStatus(false), 2000);
  };

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col font-sans">
      <NavigationHeader />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        
        {/* Header & Title Banner */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white p-6 rounded-3xl border border-slate-200 shadow-xs">
          <div className="flex items-center space-x-4">
            <div className="p-3 bg-purple-700 text-white rounded-2xl shadow-sm shrink-0">
              <Landmark className="w-7 h-7" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h1 className="text-2xl font-black text-slate-900 tracking-tight">CRA Monthly Payroll Remittance (PD7A)</h1>
                <span className="bg-purple-100 text-purple-800 text-[10px] font-black uppercase px-2.5 py-0.5 rounded-full border border-purple-200">
                  Receiver General Canada
                </span>
              </div>
              <p className="text-xs font-medium text-slate-500 mt-0.5">
                Automated monthly deduction summary for CRA Receiver General filing & Direct Funding audit reimbursement.
              </p>
            </div>
          </div>

          {/* Quick Action Buttons */}
          <div className="flex flex-wrap items-center gap-3">
            <button
              onClick={handleDownloadCsv}
              className="min-h-[44px] px-4 bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-black rounded-xl flex items-center space-x-2 transition cursor-pointer border border-slate-200"
            >
              <FileSpreadsheet className="w-4 h-4 text-emerald-700" />
              <span>Export CSV</span>
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={isGeneratingPdf}
              className="min-h-[44px] px-5 bg-purple-700 hover:bg-purple-800 text-white text-xs font-black rounded-xl flex items-center space-x-2 transition shadow-md cursor-pointer"
            >
              {isGeneratingPdf ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Download className="w-4 h-4" />
              )}
              <span>1-Click Download CRA PD7A PDF</span>
            </button>
          </div>
        </div>

        {/* Interactive Configuration Bar */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 bg-white p-5 rounded-2xl border border-slate-200 shadow-xs text-xs font-bold">
          <div className="space-y-1">
            <label className="text-slate-500 uppercase tracking-wider text-[10px] font-black">Remittance Period</label>
            <select
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              className="w-full h-10 px-3 bg-slate-50 rounded-xl border border-slate-300 font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-600"
            >
              <option value="August 2026">August 2026 (Due Sept 15)</option>
              <option value="September 2026">September 2026 (Due Oct 15)</option>
              <option value="October 2026">October 2026 (Due Nov 15)</option>
            </select>
          </div>

          <div className="space-y-1">
            <label className="text-slate-500 uppercase tracking-wider text-[10px] font-black">CRA Payroll Account (15-Digit RP)</label>
            <div className="relative">
              <input
                type="text"
                value={rpNumber}
                onChange={(e) => setRpNumber(e.target.value)}
                placeholder="12345 6789 RP0001"
                className="w-full h-10 pl-3 pr-16 bg-slate-50 rounded-xl border border-slate-300 font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-600"
              />
              <button
                type="button"
                onClick={handleCopyRp}
                className="absolute right-1 top-1 bottom-1 px-2.5 bg-slate-200 hover:bg-slate-300 text-[10px] font-black text-slate-700 rounded-lg transition cursor-pointer"
              >
                {copiedStatus ? "Copied!" : "Copy RP"}
              </button>
            </div>
          </div>

          <div className="space-y-1">
            <label className="text-slate-500 uppercase tracking-wider text-[10px] font-black">Self-Managed Employer Name</label>
            <input
              type="text"
              value={employerName}
              onChange={(e) => setEmployerName(e.target.value)}
              className="w-full h-10 px-3 bg-slate-50 rounded-xl border border-slate-300 font-bold text-slate-800 focus:outline-none focus:ring-2 focus:ring-purple-600"
            />
          </div>
        </div>

        {/* Main Printable / Capture Card */}
        <div className="max-w-4xl mx-auto w-full">
          <div
            ref={cardRef}
            className="bg-white rounded-3xl border-2 border-purple-200 p-8 sm:p-10 shadow-lg space-y-8 text-slate-900"
          >
            {/* Document Watermark / Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b-2 border-slate-900 pb-6 gap-4">
              <div className="space-y-1">
                <div className="flex items-center space-x-2">
                  <div className="w-3 h-3 bg-red-600 rounded-full" />
                  <span className="text-xs font-black uppercase tracking-widest text-slate-500">
                    Canada Revenue Agency / Agence du revenu du Canada
                  </span>
                </div>
                <h2 className="text-2xl font-black text-slate-900 tracking-tight">FORM PD7A • STATEMENT OF ACCOUNT</h2>
                <p className="text-xs font-bold text-purple-900">
                  Monthly Remittance Summary for Direct Funding Employer Payroll Deductions
                </p>
              </div>

              <div className="text-left sm:text-right bg-purple-50 p-3.5 rounded-2xl border border-purple-200">
                <p className="text-[10px] font-black text-purple-800 uppercase tracking-wider">Remittance Due Date</p>
                <p className="text-lg font-black text-purple-950">{remittanceData.dueDate}</p>
                <p className="text-[10px] text-purple-700 font-bold">Penalty applies if late</p>
              </div>
            </div>

            {/* Account Identifiers Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 bg-slate-50 p-4 rounded-2xl border border-slate-200 text-xs">
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase">Registered Employer</p>
                <p className="font-extrabold text-slate-900 mt-0.5">{employerName}</p>
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase">CRA Payroll Account (RP)</p>
                <p className="font-extrabold text-purple-900 mt-0.5 font-mono">{rpNumber}</p>
              </div>
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase">Statement Period</p>
                <p className="font-extrabold text-slate-900 mt-0.5">{period}</p>
              </div>
            </div>

            {/* Itemized Line Items Table */}
            <div className="space-y-4">
              <h3 className="text-sm font-black uppercase tracking-wider text-slate-700 border-b border-slate-200 pb-2">
                Monthly Deduction Breakdown
              </h3>

              <div className="space-y-3 text-xs font-bold">
                <div className="flex justify-between items-center py-2 border-b border-slate-100">
                  <span className="text-slate-600">Active Attendants in Remittance Period</span>
                  <span className="text-slate-900 font-black">{remittanceData.employeesCount} Employees</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-slate-100">
                  <span className="text-slate-600">Total Gross Payroll Disbursed</span>
                  <span className="text-slate-900 font-black">${remittanceData.grossPayroll.toFixed(2)}</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-slate-100">
                  <div>
                    <span className="text-slate-900">Canada Pension Plan (CPP) Contributions</span>
                    <p className="text-[11px] text-slate-500 font-medium">
                      Employee Portion (${remittanceData.cppEmployee.toFixed(2)}) + Employer Match 1.0x (${remittanceData.cppEmployer.toFixed(2)})
                    </p>
                  </div>
                  <span className="text-slate-900 font-black">${(remittanceData.cppEmployee + remittanceData.cppEmployer).toFixed(2)}</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-slate-100">
                  <div>
                    <span className="text-slate-900">Employment Insurance (EI) Premiums</span>
                    <p className="text-[11px] text-slate-500 font-medium">
                      Employee Portion (${remittanceData.eiEmployee.toFixed(2)}) + Employer Statutory Match 1.4x (${remittanceData.eiEmployer.toFixed(2)})
                    </p>
                  </div>
                  <span className="text-slate-900 font-black">${(remittanceData.eiEmployee + remittanceData.eiEmployer).toFixed(2)}</span>
                </div>

                <div className="flex justify-between items-center py-2 border-b border-slate-100">
                  <div>
                    <span className="text-slate-900">Federal & Provincial Income Tax Withheld</span>
                    <p className="text-[11px] text-slate-500 font-medium">Calculated per CRA T4032 Payroll Deductions Tables</p>
                  </div>
                  <span className="text-slate-900 font-black">${remittanceData.incomeTax.toFixed(2)}</span>
                </div>
              </div>
            </div>

            {/* Total Remittance Callout Box */}
            <div className="p-6 bg-purple-900 text-white rounded-2xl shadow-md flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <div className="flex items-center space-x-2">
                  <ShieldCheck className="w-5 h-5 text-purple-300" />
                  <p className="text-xs font-black uppercase tracking-widest text-purple-200">
                    Total CRA Remittance Amount Due
                  </p>
                </div>
                <p className="text-xs text-purple-200 mt-1">
                  Payable online via CRA My Business Account or financial institution online banking.
                </p>
              </div>
              <p className="text-3xl font-black text-white shrink-0">
                ${remittanceData.totalRemittance.toFixed(2)} CAD
              </p>
            </div>

            {/* Footer Audit Declaration */}
            <div className="pt-4 border-t border-slate-200 flex flex-col sm:flex-row justify-between text-[11px] text-slate-500 gap-2">
              <div className="flex items-center space-x-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
                <span>Verified DirectCare Hub Audit Ledger • Formatted per CRA PD7A standards</span>
              </div>
              <p>Generated: {new Date().toLocaleDateString("en-CA")}</p>
            </div>
          </div>
        </div>

        {/* How To Submit Instructions Card */}
        <div className="max-w-4xl mx-auto w-full bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 space-y-4">
          <div className="flex items-center space-x-3 text-slate-900">
            <HelpCircle className="w-5 h-5 text-purple-700" />
            <h3 className="text-base font-black">How to Submit Your Monthly Remittance to CRA</h3>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs font-medium text-slate-600">
            <div className="p-4 bg-slate-50 rounded-2xl border border-slate-200 space-y-1">
              <span className="text-purple-700 font-black text-sm">Step 1</span>
              <p className="font-bold text-slate-900">Copy 15-Digit RP Number</p>
              <p className="text-[11px] leading-relaxed">Copy your CRA Payroll account number (<span className="font-mono text-purple-900 font-bold">{rpNumber}</span>) generated above.</p>
            </div>

            <div className="p-4 bg-slate-50 rounded-2xl border border-slate-200 space-y-1">
              <span className="text-purple-700 font-black text-sm">Step 2</span>
              <p className="font-bold text-slate-900">Pay Via Online Banking</p>
              <p className="text-[11px] leading-relaxed">Log into RBC, TD, Scotiabank, BMO, or CIBC. Add payee: <strong className="text-slate-900">CRA Payroll Deductions - Monthly Remittance</strong>.</p>
            </div>

            <div className="p-4 bg-slate-50 rounded-2xl border border-slate-200 space-y-1">
              <span className="text-purple-700 font-black text-sm">Step 3</span>
              <p className="font-bold text-slate-900">Attach PDF to Quarterly CILT Claim</p>
              <p className="text-[11px] leading-relaxed">Attach the downloaded 1-click PDF summary to your quarterly Direct Funding invoice submission for full grant reimbursement.</p>
            </div>
          </div>
        </div>

      </main>
    </div>
  );
}

